version: '3.3'

services:
  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    ports:
      - "8080:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_URL=https://builder.${DOMAIN}
      - NEXT_PUBLIC_VIEWER_URL=https://viewer.${DOMAIN}
      - ENCRYPTION_SECRET=${ENCRYPTION_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}

  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    ports:
      - "8081:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_VIEWER_URL=https://viewer.${DOMAIN}
      - ENCRYPTION_SECRET=${ENCRYPTION_SECRET}
